#!/usr/bin/env python3
"""Write web/shared/metrics.js: advance widths for the fonts pages are set in.

A PDF made here uses the standard Helvetica, Times and Courier, which every PDF
reader has, and the preview on screen uses Liberation Sans, Serif and Mono,
which are drawn to exactly the same widths. So one table of widths lays a line
out identically in both, and the line breaks on screen are the line breaks in
the PDF. The widths are read from the Liberation fonts once, here, and kept.
"""
import json, os, sys
from fontTools.ttLib import TTFont

DIR = '/usr/share/fonts/truetype/liberation'
FACES = {
    'sans': ['LiberationSans-Regular', 'LiberationSans-Bold', 'LiberationSans-Italic', 'LiberationSans-BoldItalic'],
    'serif': ['LiberationSerif-Regular', 'LiberationSerif-Bold', 'LiberationSerif-Italic', 'LiberationSerif-BoldItalic'],
    'mono': ['LiberationMono-Regular', 'LiberationMono-Bold', 'LiberationMono-Italic', 'LiberationMono-BoldItalic'],
}
# WinAnsiEncoding: the characters a standard PDF font can show.
winansi = {i: chr(i) for i in range(32, 127)}
for i in range(160, 256):
    winansi[i] = bytes([i]).decode('latin-1')
extra = {0x80: '€', 0x82: '‚', 0x83: 'ƒ', 0x84: '„', 0x85: '…', 0x86: '†',
         0x87: '‡', 0x88: 'ˆ', 0x89: '‰', 0x8a: 'Š', 0x8b: '‹', 0x8c: 'Œ',
         0x8e: 'Ž', 0x91: '‘', 0x92: '’', 0x93: '“', 0x94: '”', 0x95: '•',
         0x96: '–', 0x97: '—', 0x98: '˜', 0x99: '™', 0x9a: 'š', 0x9b: '›',
         0x9c: 'œ', 0x9e: 'ž', 0x9f: 'Ÿ'}
winansi.update(extra)
chars = ''.join(winansi[k] for k in sorted(winansi))

out = {}
for fam, faces in FACES.items():
    out[fam] = []
    for face in faces:
        f = TTFont(os.path.join(DIR, face + '.ttf'))
        upm = f['head'].unitsPerEm
        cmap = f.getBestCmap()
        hmtx = f['hmtx']
        widths = []
        for ch in chars:
            g = cmap.get(ord(ch))
            w = hmtx[g][0] if g else hmtx['.notdef'][0]
            widths.append(round(w * 1000 / upm))
        out[fam].append(widths)

codes = [k for k in sorted(winansi)]
with open(sys.argv[1], 'w') as fh:
    fh.write('// Generated by tools/make-metrics.py - do not edit by hand.\n')
    fh.write('// Advance widths in 1/1000 em for the WinAnsi characters, per family, in the\n')
    fh.write('// order regular, bold, italic, bold italic.\n\n')
    fh.write('export const CHARS = ' + json.dumps(chars) + ';\n')
    fh.write('export const CODES = ' + json.dumps(codes) + ';\n')
    fh.write('export const WIDTHS = {\n')
    for fam in FACES:
        fh.write('  ' + fam + ': [\n')
        for w in out[fam]:
            fh.write('    ' + json.dumps(w, separators=(',', ':')) + ',\n')
        fh.write('  ],\n')
    fh.write('};\n')
